version: "3.1"

services:
  node:
    image: node-express:latest
    container_name: ExpressApp
    ports:
      - 4000:4000
    environment:
      MONGO_URI: mongodb://root:secret@mongo:27017/devops-e2e?authSource=admin

  mongo:
    image: mongo:latest
    container_name: MongoDB
    volumes:
      - ../data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express:latest
    container_name: MongoExpress
    ports:
      - 4001:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/

  jenkins:
    container_name: JenkinsCI
    image: jenkins/jenkins:lts
    ports:
      - 4002:8080
  
  # inbound-agent:
  #   container_name: InboundAgent
  #   image: jforge/jenkins-inbound-agent:latest
  #   privileged: true
  #   environment:
  #     DIND: "true"
  #     TINI_SUBREAPER: "true"
  #     JENKINS_WEB_SOCKET: "true"
  #     JENKINS_URL: "http://jenkins:8080"
  #     JENKINS_AGENT_NAME: "inbound-agent"
  #     JENKINS_SECRET: "e2ca1091e6bbb791ca0caece89041cab42aa7bf4362f81877c274ffa7fdcf21e"
