version: '3.1'

services:
  node:
    image: node-express:latest
    container_name: ExpressApp
    ports:
      - 4000:4000
    environment:
      MONGO_URI: mongodb://root:secret@mongo:27017/devops-e2e?authSource=admin

  mongo:
    image: mongo:latest
    container_name: MongoDB
    volumes:
      - ../data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express:latest
    container_name: MongoExpress
    ports:
      - 4001:8081
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/