pipeline {
    agent any

    stages {
        stage('Docker Images') {
            steps {
                sh 'docker images'
            }
        }
        stage('Path') {
            steps {
                sh 'pwd'
            }
        }
        stage('create txt file') {
            steps {
                sh 'touch yakir.txt'
            }
        }
        stage('filled txt file') {
            steps {
                sh 'echo "Trigger by github" > ./yakir.txt'
            }
        }
    }
}
