pipeline {
    agent {
        label 'inbound-agent'
    }

    stages {
        // Stage that check selenium script isAlive.py
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
