apiVersion: v1
kind: Service
metadata:
  name: school-loadbalancer
  namespace: school
  labels:
    nginx: my-nginx
spec:
  selector:
    nginx: my-nginx
  ports:
  - protocol: TCP
    port: 3050
    targetPort: 80
  type: LoadBalancer