apiVersion: v1
kind: Pod
metadata:
  name: school-pod
  namespace: school
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: nginx:latest
    ports:
    - containerPort: 80

# kubectl get pods || kubectl get pods -n {namespace}