apiVersion: v1
kind: Service
metadata:
  name: school-service
  namespace: school
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

# kubectl get services || kubectl get svc